name: Build a Docker image and publish to Docker Hub

on:
  push:
    branches: [master]

jobs:
  build_container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Build and push container
        uses: docker/build-push-action@v4
        with:
          context: ./python-docker
          file: ./python-docker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/python-ci-test:latest

  test_container:
    needs: build_container
    runs-on: ubuntu-latest
    steps:
      - name: Pull container
        run: docker pull alu0101124896/python-ci-test
      
      - name: Run container
        run: docker run -dp 8000:5000 docker.io/alu0101124896/python-ci-test:latest

      - name: Test GET request
        run: diff <(curl localhost:8000) <(echo -n "Hello, Docker!")
